services:
    mii-aktin-report-client:
        build: .
        environment:
            - FHIR_BASE_URL=${MII_REPORT_CLIENT_FHIR_BASE_URL}
            - FHIR_USER=${MII_REPORT_CLIENT_FHIR_USER}
            - FHIR_PW=${MII_REPORT_CLIENT_FHIR_PW}
            - FHIR_TOKEN=${MII_REPORT_CLIENT_FHIR_TOKEN}
            - HTTPS_PROXY=${MII_REPORT_CLIENT_HTTPS_PROXY}
            - BROKER_ENDPOINT_URI=${MII_REPORT_BROKER_ENDPOINT_URI}
            - CLIENT_AUTH_PARAM=${MII_REPORT_CLIENT_AUTH_PARAM}
        volumes:
            - ./report-queries.json:/opt/reportclient/report-queries.json