services:
    mii-aktin-central-report-client:
        build: .
        environment:
            - BROKER_ENDPOINT_URI=${MII_REPORT_BROKER_ENDPOINT_URI}
            - CLIENT_AUTH_PARAM=${MII_REPORT_CLIENT_AUTH_PARAM}
        volumes:
            - ./reports:/opt/reportclient/reports
