name: Docker

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**

jobs:

  release-central-broker-client:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Version
      id: prep
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./central-broker-client
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/medizininformatik-initiative/mii-site-report-central-broker-client:latest
          ghcr.io/medizininformatik-initiative/mii-site-report-central-broker-client:${{ steps.prep.outputs.version }}
        push: true

  release-site-client:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Version
      id: prep
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./site-client
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/medizininformatik-initiative/mii-site-report-site-client:latest
          ghcr.io/medizininformatik-initiative/mii-site-report-site-client:${{ steps.prep.outputs.version }}
        push: true
